import = ["~/.config/alacritty/theme.toml", "~/AppData/Roaming/alacritty/theme.toml"]
live_config_reload = true

[bell]
command = "None"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 500
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "Block"

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[window]
opacity = 0.8
