#!/usr/bin/env bash

# Remove special charcters from the name
export normalized=$(echo "$1" | tr [:upper:] [:lower:] | tr -d '[:punct:]' | tr ' ' '_')
export normalized_=$(echo $normalized | tr '_' '-')
export version=$(./version.sh)

dots=$( cd -- "$( dirname -- "$0" )" &> /dev/null && pwd )
if test -f "/proc/sys/fs/binfmt_misc/WSLInterop"; then
  local=$(echo "$dots" | sed 's/\/mnt\/\(.\)/\1:/')
else
  local=$(echo "$dots")
fi

### Neovim ###
echo "let g:theme_style = '$1'" > $dots/nvim/theme.vim

### Alacritty ###
echo "general.import = [\"$local/themes/$version/alacritty/$normalized_.toml\"]" > $dots/alacritty/theme.toml

### Helix ###
echo "inherits = \"$normalized\"

\"ui.background\" = {}" > "$local/helix/themes/theme.toml"

# Ignore linux only programs if running in WSL.
if test -f "/proc/sys/fs/binfmt_misc/WSLInterop"; then
  exit 0
fi

### Ghostty ###
echo "theme = $local/themes/$version/ghostty/$normalized" > $local/ghostty/theme

### Hypr ###
ln -sf $local/themes/$version/hypr/terminal.conf $local/hypr/terminal.conf
ln -sf $local/themes/$version/hypr/$normalized_.conf $local/hypr/theme.conf
pgrep Hyprland &> /dev/null && hyprctl reload &> /dev/null

### Parse colours ###
colours=$(cat "$local/hypr/theme.conf")

bg0=$(echo "$colours" | rg Bg0 | sed "s/.* = \(.*\)/\1/g")
bg2=$(echo "$colours" | rg Bg2 | sed "s/.* = \(.*\)/\1/g")
comp0=$(echo "$colours" | rg Comp0 | sed "s/.* = \(.*\)/\1/g")
plain=$(echo "$colours" | rg Plain | sed "s/.* = \(.*\)/\1/g")
primary0=$(echo "$colours" | rg Primary0 | sed "s/.* = \(.*\)/\1/g")
primary1=$(echo "$colours" | rg Primary1 | sed "s/.* = \(.*\)/\1/g")
primary2=$(echo "$colours" | rg Primary2 | sed "s/.* = \(.*\)/\1/g")
primary3=$(echo "$colours" | rg Primary3 | sed "s/.* = \(.*\)/\1/g")

### Bemenu ###
echo "bg0=\"#$bg0\""           >  scripts/bemenu/theme.sh
echo "plain=\"#$plain\""       >> scripts/bemenu/theme.sh
echo "primary0=\"#$primary0\"" >> scripts/bemenu/theme.sh

### Quickshell ###

[[ -d $local/quickshell ]] && echo "// WARNING: generated by set_theme.sh, manual edits will not persist.

pragma Singleton
import Quickshell
Singleton {
  readonly property string bg0: \"#$bg0\";
  readonly property string bg2: \"#$bg2\";
  readonly property string plain: \"#$plain\";
  readonly property string comp0: \"#$comp0\";
  readonly property string primary0: \"#$primary0\";
  readonly property string primary1: \"#$primary1\";
  readonly property string primary2: \"#$primary2\";
  readonly property string primary3: \"#$primary3\";
}
" > $local/quickshell/Theme.qml
