theme = "theme"

[editor]
line-number = "relative"
bufferline = "always"
color-modes = true

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "version-control", "file-modification-indicator"]
center = []
right = ["diagnostics", "selections", "register", "file-line-ending", "position", "total-line-numbers", "file-encoding"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
