// WARNING: generated by set_theme.sh, manual edits will not persist.

pragma Singleton
import Quickshell

Singleton {
    readonly property string bg0: "#281b27"
    readonly property string plain: "#faeeeb"
    readonly property string comp0: "#ffcc66"
    readonly property string primary0: "#ff3388"
    readonly property string primary1: "#ff668c"
    readonly property string primary2: "#ff99a2"
    readonly property string primary3: "#ffd0cc"
}
